inherit_from:
  - https://shopify.github.io/ruby-style-guide/rubocop.yml

require: 
  - rubocop-minitest
  - rubocop-rake

Naming/FileName:
  Exclude:
    - lib/ruby-limiter.rb

AllCops:
  TargetRubyVersion: 2.7
